name: DEB and RMP packages 

on:
  push:
    branches:
      - iss53_deb_rpm_packages

env:
  VERSION: "1.7.0"
  WDIR: "/home/runner/work/fwcloud-ui/fwcloud-ui"
  TGZ: "fwcloud.tar.gz"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download FWCloud-Websrv
        working-directory: ${{ env.WDIR }}
        run: wget -c -O fwcloud-websrv.zip https://github.com/soltecsis/fwcloud-websrv/archive/refs/heads/main.zip

      - name: Download FWCloud-UI
        working-directory: ${{ env.WDIR }}
        run: wget -c -O fwcloud-ui.zip https://github.com/soltecsis/fwcloud-ui/archive/refs/heads/main.zip

      - name: Build FWCloud-Websrv
        working-directory: ${{ env.WDIR }}
        run: |
          unzip fwcloud-websrv.zip && rm -f fwcloud-websrv.zip
          mkdir fwcloud
          mv fwcloud-websrv-main fwcloud/websrv
          cd fwcloud/websrv
          npm install && npm run build
          rm -rf .github .eslintrc.js .gitignore .prettierrc .vscode test src

      - name: Build FWCloud-UI
        working-directory: ${{ env.WDIR }}
        run: |
          unzip fwcloud-ui.zip && rm -f fwcloud-ui.zip
          mv fwcloud-ui-main fwcloud/ui
          cd fwcloud/ui
          rm -rf .github docker

      - name: Create ${{ env.TGZ }} file
        working-directory: ${{ env.WDIR }}
        run: tar zcpf ${{ env.TGZ }} fwcloud

      - name: Upload ${{ env.TGZ }}
        uses: actions/upload-artifact@v3
        with:
          name: tgz
          path: ${{ env.WDIR }}/${{ env.TGZ }}

  deb-package:
    needs: [build]
    runs-on: ubuntu-latest
    name: DEB package
    steps:
      - uses: actions/checkout@v3

      - name: Download ${{ env.TGZ }}
        uses: actions/download-artifact@v3

      - name: Extract content of ${{ env.TGZ }} file
        working-directory: ${{ env.WDIR }}
        run: |
          mv tgz/${{ env.TGZ }} .
          tar zxpf ${{ env.TGZ }}

      - name: List directory content
        working-directory: ${{ env.WDIR }}
        run: ls -lha ./fwcloud/

      - name: Generate DEB package
        uses: bpicode/github-action-fpm@master
        with:
          fpm_args: './fwcloud/=/opt/fwcloud/'
          fpm_opts: | 
            -C /github/workspace
            -p fwcloud-ui-${{ env.VERSION }}-any.deb
            --architecture all
            --name fwcloud-ui
            --version ${{ env.VERSION }}
            --description "Web user interface of the FWCloud project."
            --url "https://fwcloud.net"
            --maintainer "Carles Munyoz <cmunyoz@soltecsis.com>"
            -t deb
            -s dir

      - name: Upload DEB package
        uses: actions/upload-artifact@v3
        with:
          name: deb-package
          path: ${{ env.WDIR }}/*.deb

  deb-to-packagecloud:
    needs: [deb-package]
    runs-on: ubuntu-latest
    name: DEB to Packagecloud
    strategy:
      matrix:
        dist: [any/any, ubuntu/bionic, ubuntu/cosmic]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download DEB package
        uses: actions/download-artifact@v3

      - name: List packages
        run: ls -lha ./deb-package/

      - name: ${{ matrix.dist }}
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: ./deb-package/*.deb
          PACKAGECLOUD-USERNAME: ${{ secrets.PACKAGECLOUD_USERNAME }}
          PACKAGECLOUD-REPO: FWCloud
          PACKAGECLOUD-DISTRIB: ${{ matrix.dist }}
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
