name: DEB and RMP packages 

on:
  push:
    branches:
      - iss53_deb_rpm_packages

env:
  TESTTT: "1.7.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Download FWCloud-Websrv
      working-directory: /home/runner/work/fwcloud-ui/fwcloud-ui
      run: wget -c -O fwcloud-websrv.zip https://github.com/soltecsis/fwcloud-websrv/archive/refs/heads/main.zip

    - name: Download FWCloud-UI
      working-directory: /home/runner/work/fwcloud-ui/fwcloud-ui
      run: wget -c -O fwcloud-ui.zip https://github.com/soltecsis/fwcloud-ui/archive/refs/heads/main.zip

    - name: Build FWCloud-Websrv
      working-directory: /home/runner/work/fwcloud-ui/fwcloud-ui
      run: |
        unzip fwcloud-websrv.zip && rm -f fwcloud-websrv.zip
        mkdir fwcloud
        mv fwcloud-websrv-main fwcloud/websrv
        cd fwcloud/websrv
        npm install && npm run build
        rm -rf .github .eslintrc.js .gitignore .prettierrc .vscode test src

    - name: Build FWCloud-UI
      working-directory: /home/runner/work/fwcloud-ui/fwcloud-ui
      run: |
        unzip fwcloud-ui.zip && rm -f fwcloud-ui.zip
        mv fwcloud-ui-main fwcloud/ui
        cd fwcloud/ui
        rm -rf .github docker

    - name: DEB package
      uses: bpicode/github-action-fpm@master
      with:
        fpm_args: './fwcloud/=/opt/fwcloud/'
        fpm_opts: > 
          -C /github/workspace
          -p fwcloud-ui-${TESTTT}-any.deb
          --architecture all
          --name fwcloud-ui
          --version $TESTTT
          --description "Web user interface of the FWCloud project."
          --url "https://fwcloud.net"
          --maintainer "Carles Munyoz <cmunyoz@soltecsis.com>"
          -t deb
          -s dir