name: DEB and RMP packages 

on:
  push:
    branches:
      - iss53_deb_rpm_packages

env:
  TGZ: "fwcloud.tar.gz"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Download FWCloud-Websrv
        run: wget -c -O fwcloud-websrv.zip https://github.com/soltecsis/fwcloud-websrv/archive/refs/heads/main.zip

      - name: Download FWCloud-UI
        run: wget -c -O fwcloud-ui.zip https://github.com/soltecsis/fwcloud-ui/archive/refs/heads/main.zip

      - name: Build FWCloud-Websrv
        run: |
          unzip fwcloud-websrv.zip && rm -f fwcloud-websrv.zip
          mkdir fwcloud
          mv fwcloud-websrv-main fwcloud/websrv
          cd fwcloud/websrv
          npm install && npm run build
          rm -rf .github .eslintrc.js .gitignore .prettierrc .vscode test src

      - name: Build FWCloud-UI
        run: |
          unzip fwcloud-ui.zip && rm -f fwcloud-ui.zip
          mv fwcloud-ui-main fwcloud/ui
          cd fwcloud/ui
          rm -rf .github docker

      - name: Create ${{ env.TGZ }} file
        run: tar zcpf ${{ env.TGZ }} fwcloud

      - name: Upload ${{ env.TGZ }}
        uses: actions/upload-artifact@v3
        with:
          name: tgz
          path: ${{ env.TGZ }}

  deb-rpm-package:
    needs: [build]
    runs-on: ubuntu-latest
    name: Package
    strategy:
      matrix:
        pkg: [rpm]
    steps:
      - uses: actions/checkout@v3

      - name: Get fwcloud-ui version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Download ${{ env.TGZ }}
        uses: actions/download-artifact@v3
        with:
          name: tgz

      - name: Extract content of ${{ env.TGZ }} file
        run: tar zxpf ${{ env.TGZ }}

      - name: List directory content
        run: ls -lha ./fwcloud/

      - name: Generate ${{ matrix.pkg }} package
        uses: bpicode/github-action-fpm@master
        with:
          fpm_args: './fwcloud/=/opt/fwcloud/'
          fpm_opts: | 
            -C /github/workspace
            -p fwcloud-ui-${{ steps.package-version.outputs.current-version}}-any.${{ matrix.pkg }}
            --architecture all
            --name fwcloud-ui
            --version ${{ steps.package-version.outputs.current-version}}
            --description "Web user interface of the FWCloud project."
            --url "https://fwcloud.net"
            --maintainer "Carles Munyoz <cmunyoz@soltecsis.com>"
            -t ${{ matrix.pkg }}
            -s dir

      - name: Upload ${{ matrix.pkg }} package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.pkg }}-package
          path: ./*.${{ matrix.pkg }}

  deb-to-packagecloud:
    needs: [deb-rpm-package]
    runs-on: ubuntu-latest
    name: DEB to Packagecloud
    strategy:
      matrix:
        dist: [any/any]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download DEB package
        uses: actions/download-artifact@v3
        with:
          name: deb-package

      - name: List packages
        run: ls -lha *.deb

      - name: ${{ matrix.dist }}
        uses: danielmundi/upload-packagecloud@v1
        with:
          PACKAGE-NAME: ./*.deb
          PACKAGECLOUD-USERNAME: ${{ secrets.PACKAGECLOUD_USERNAME }}
          PACKAGECLOUD-REPO: FWCloud
          PACKAGECLOUD-DISTRIB: ${{ matrix.dist }}
          PACKAGECLOUD-TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}
